# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_stateapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
