# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0004_auto_20160728_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateapp',
            old_name='ops',
            new_name='operations',
        ),
    ]
