# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0005_auto_20160728_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='current',
            field=models.CharField(max_length=200),
        ),
    ]
